### PR TITLE
hide map on mobile, fix feedback button style

### PR DESCRIPTION
**Pull request by chloeleichen**
### Checklist
- [x] I've updated CHANGES.md with what I changed.
- [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column

do no load map on mobile: 
screen shot 2018-06-04 at 12 35 31 pm

Also updated File API links:
screen shot 2018-06-04 at 5 01 20 pm

### CODE REVIEW

**Comment by AlexGilleran** [comment]
Looks OK to me - over to you @tkeuneman as requested, preview is at http://issue-1115-mobile-map.magda-dev.terria.io/dataset/ds-dga-49d40919-20ea-4d06-b36f-ed95d88cbce8/details?q=

**Comment by tkeuneman** [comment]
screenshot_20180607-105341

- [ ] Align icons with the middle of the text in the buttons
- [ ] Make button border px consistent with secondary buttons

**Comment by chloeleichen** [comment]
button alignment:
screen shot 2018-06-12 at 11 06 59 am

**Comment by chloeleichen** [comment]
made placeholder consistent & visible 
screen shot 2018-06-12 at 11 16 33 am

**Comment by AlexGilleran** [comment]
@tkeuneman http://issue-1115-mobile-map.magda-dev.terria.io

**Comment by AlexGilleran** [comment]
Tash is away this week so merging based on it looking right to me 🤷‍♂️ :shipit:

**Pull request merged**
