### PR TITLE
Added tooltip to future dates

### PR DESCRIPTION
**Pull request by sukhrajghuman**
### What this PR does

Added tooltip filter to explain future dates when they are selected in the datepicker

### Checklist
- [x] There are unit tests to verify my changes are correct | Unit tests aren't applicable (delete one)
- [x] I've updated CHANGES.md with what I changed.
- [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column

### CODE REVIEW

**Comment by chloeleichen** [comment]
@sukhrajghuman can you attach a screenshot for what you have done? The description is a bit confusing

**Comment by chloeleichen** [comment]
screen shot 2018-05-15 at 2 15 01 pm
1. I think it's better to have normal font weight for the tooltip text? It's a bit hard to read.
2. Adding the icon on the side squeeze the second date picker and make the two date picker not even width. Can you make them the same width please? Maybe by moving the question mark icon inside the input element?

**Comment by sukhrajghuman** [comment]
Hmmm...not sure why tooltip text is in bold on your screen...
here is what i see:

image

**Comment by AlexGilleran** [comment]
Tooltip text looks fine to me, but it is showing even for dates in the past:

image

**Pull request merged**
