### PR TITLE
Issue/728: Adjusted recent search box style & added delete button etc.

### PR DESCRIPTION
**Pull request by t83714**
### What this PR does

- Adjusted recent search box style #728 
- Added delete button on the recent search box
- Same search text with different filters will be considered as same searches #723

### Checklist
- [x] There are unit tests to verify my changes are correct | Unit tests aren't applicable (delete one)
- [x] I've updated CHANGES.md with what I changed.
- [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column

### CODE REVIEW

**Comment by chloeleichen** [comment]
Hi @t83714  It's missing the "X: icon 
screen shot 2018-04-06 at 9 39 37 am

**Comment by t83714** [comment]
Delete button added

**Comment by AlexGilleran** [comment]
Are you happy with this now @chloeleichen ? :)

**Comment by t83714** [comment]
I think everyone should be happy with the changes
Merge it now~

**Pull request merged**
