### PR TITLE
Issue611 mobile search

### PR DESCRIPTION
**Pull request by chloeleichen**
### Checklist

- [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column

### CODE REVIEW

**Comment by AlexGilleran** [comment]
> Apply/cancel should be visible at all times (currently, on a large pixel, I have to scroll to see it

This is still off the screen for me - but I don't see any design for where it should move to? @tkeuneman ?

**Comment by tkeuneman** [comment]
@AlexGilleran Ideally the website will recognise the height of the browser, show the number of fields that they can show while keeping the apply/cancel visible. I can mock this up, if you like.

**Comment by AlexGilleran** [comment]
Yeah sounds good :)

**Comment by AlexGilleran** [comment]
@chloeleichen 

https://user-images.githubusercontent.com/2201814/38653568-c31763b4-3e4e-11e8-9b2c-9d648aaf54dc.png

**Comment by chloeleichen** [comment]
img_4203
Made facet box much shorter on mobile
The format box is onscured by feedback button, but since feedback button will be removed on mobile soon, I won't make it any shorter

**Pull request merged**
