### PR TITLE
style org page

### PR DESCRIPTION
**Pull request by chloeleichen**
### What this PR does
screen shot 2018-05-29 at 4 26 05 pm
### Checklist

- [x] I've updated CHANGES.md with what I changed.
- [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column

### CODE REVIEW

**Comment by AlexGilleran** [comment]
I'm happy with this code-wise - @tkeuneman or @philipgrimmett can you QA the UI part? it's at http://org-page.magda-dev.terria.io/organisations

**Comment by philipgrimmett** [comment]
Looking good! Seems like the Heading styles are different from the About page though? Also the heading should be Sentence case, not upper case.

It would be great to have the number of datasets listed under each publisher (in the same style as on the datasets results page), but not essential if we're short on time.

**Comment by tkeuneman** [comment]
+1 to what @philipgrimmett suggested. We can do the dataset count under a seperate ticket.

**Comment by chloeleichen** [comment]
@philipgrimmett the page heading on about page is black, should I make them all purple?

**Comment by chloeleichen** [comment]
done: 
screen shot 2018-06-04 at 5 07 52 pm

**Pull request merged**
