### PR TITLE
Made the banner tag opted out users with `noPreview` cookie set to true.

### PR DESCRIPTION
**Pull request by AlexGilleran**
### What this PR does
Tags people who click the "go back" link with a `noPreview` cookie that VWO can pick up, so they don't end up getting redirected.

### Checklist
- [x] Unit tests aren't applicable (delete one)
- [x] I've updated CHANGES.md with what I changed.
- [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column

### CODE REVIEW

**Comment by t83714** [comment]
Tested the followings:
1> `noPreview` cookie is set after link has been clicked
2> User will still be redirect to https://data.gov.au/ after click

**Comment by AlexGilleran** [comment]
@t83714 are you happy with this then? If so please merge :)

**Comment by t83714** [comment]
Had done tests previously and everything is OK. 
Will just wait a few more minutes until Travis build complete

**Comment by AlexGilleran** [comment]
Cool beans :)

**Pull request merged**
