### PR TITLE
Stopped open data rating always showing 0 stars

### PR DESCRIPTION
**Pull request by AlexGilleran**
### What this PR does
Right now the star ratings only show 0 stars because at some point the `QualityIndicator` component, which translated from fractions of 1 to numbers of stars, was removed at some point. This reinstates it and does some other housekeeping around the star ratings - particularly making the link for the tooltip on the questionmark (the link in the tooltip text isn't clickable), and fixing the alignment.

### Checklist
- [x] Unit tests aren't applicable (delete one)
- [x] I've updated CHANGES.md with what I changed.
- [x] I've linked this PR to an issue in ZenHub (or there is no issue) and dragged it to the _Pull Request_ column

### CODE REVIEW

**Comment by t83714** [comment]
@AlexGilleran 

Tested on gitlab and it looks good!

Only problem is most datasets on 1st page (when search *) show 5 stars but on dataset page show 3 stars.

e.g. http://974-0-star-ratings.magda-dev.terria.io/dataset/ds-dga-52c7294f-dfdc-410e-ba83-539b0bf83931/details?q=*

It seems search API return 0.91 for it but registry return link-rating aspect as 0.6.

**Comment by AlexGilleran** [comment]
😬 I assume that's because it pulled an out-of-date copy of the search index when it created the 974-0-star-ratings, will refresh the search index and see if it's still present.

**Comment by AlexGilleran** [comment]
@t83714 should be consistent now 👍

**Comment by t83714** [comment]
Tested on gitlab~ All good now~

**Pull request merged**
